
name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@master
        with:
          repository: gismo/gismo
          ref: stable
          path: ./gismo

      - uses: actions/checkout@master
        with:
          path: ./gismo/optional/${{ github.event.repository.name }}
          #token: ${{ secrets.GH_PAT }}

      # Step to install preCICE
      - name: Install preCICE
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libeigen3-dev libxml2-dev libboost-all-dev petsc-dev python3-dev python3-numpy
          wget https://github.com/precice/precice/archive/v3.1.2.tar.gz
          tar -xzvf v3.1.2.tar.gz
          cd precice-3.1.2
          cmake --preset=production  # Configure using the production preset
          cd build
          make -j 10
          sudo make install
          precice_DIR=$(pwd)
      # Step to install preCICE
      - name: Install preCICE for mac
        if: runner.os == 'macOS'
        run: |
          brew install cmake eigen libxml2 boost petsc openmpi python3 numpy
          wget https://github.com/precice/precice/archive/v3.1.2.tar.gz
          tar -xzvf v3.1.2.tar.gz
          cd precice-3.1.2
          cmake --preset=production  # Configure using the production preset
          cd build
          make -j 10
          sudo make install
          precice_DIR=$(pwd)
      - name: "Run for ${{ matrix.os }}"
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          # Use the precice_DIR set from the environment variable
          ctest -S ${{ github.event.repository.name }}/gismo/cmake/ctest_script.cmake \
          -D CMAKE_POLICY_VERSION_MINIMUM=3.5 \
          -D CTEST_BUILD_NAME="${{ github.event.repository.name }}_actions_$GITHUB_RUN_NUMBER" \
          -D CTEST_SITE="${{ matrix.os }}_[actions]" \
          -D CTEST_USE_LAUNCHERS=OFF \
          -D CMAKE_ARGS="-DCMAKE_BUILD_TYPE=$BUILD_TYPE;-DCMAKE_CXX_STANDARD=11;-DGISMO_WITH_XDEBUG=ON;-DGISMO_BUILD_UNITTESTS=ON;-Dprecice_DIR=$precice_DIR" \
          -D GISMO_OPTIONAL="gsElasticity\\;${{ github.event.repository.name }}" -Q
          
