name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false 
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gismo/gismo
          ref: stable
          path: ./gismo

      - uses: actions/checkout@v3
        with:
          path: ./gismo/optional/${{ github.event.repository.name }}
          # Uncomment token if using a private repo
          # token: ${{ secrets.GH_PAT }}
          
      - name: Install preCICE (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev \
          libeigen3-dev libgtest-dev libhdf5-dev libclang-dev libopenmpi-dev \
          libpython3-dev petsc
          cd /tmp
          git clone https://github.com/precice/precice.git
          cd precice
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install

      - name: Display Directory Structure
        run: |
          echo "Listing root directory..."
          ls -la
          echo "Listing gismo directory..."
          ls -la ./gismo

      - name: Run Tests for ${{ matrix.os }}
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          set -x  # Enable debug mode
          ctest -S ${{ github.event.repository.name }}/gismo/cmake/ctest_script.cmake \
          -D CTEST_BUILD_NAME="${{ github.event.repository.name }}_actions_$GITHUB_RUN_NUMBER" \
          -D CTEST_SITE="${{ matrix.os }}_[actions]" \
          -D CMAKE_ARGS="-DCMAKE_BUILD_TYPE=$BUILD_TYPE;-DCMAKE_CXX_STANDARD=11;-DGISMO_WITH_XDEBUG=ON;-DGISMO_BUILD_UNITTESTS=ON" \
          -D GISMO_OPTIONAL="${{ github.event.repository.name }}" \
          --output-on-failure  # Show detailed output on failure
